openapi: 3.0.4
info:
  title: starwars-api
  description: Get the name of a Star Wars entity
  version: 1.0.0
x-google-api-management:
  backends:
    app:
      address: https://backend-python-fastapi-powerofdata-532303642805.us-central1.run.app/
      pathTranslation: APPEND_PATH_TO_ADDRESS
      protocol: "http/1.1"
x-google-backend: app
paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: health
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: string
  /films:
    get:
      summary: Get a list of films
      operationId: getFilms
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /people:
    get:
      summary: Get a list of people
      operationId: getPeople
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /planets:
    get:
      summary: Get a list of planets
      operationId: getPlanets
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /starships:
    get:
      summary: Get a list of starships
      operationId: getStarships
      responses:
        '200':    
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /vehicles:
    get:
      summary: Get a list of vehicles
      operationId: getVehicles
      responses:
        '200':    
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /species:
    get:
      summary: Get a list of species
      operationId: getSpecies
      responses:
        '200':    
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string